#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds a massive, 3500+ word Turkish-English offline dictionary
including all Oxford 3000, 9th grade Fly Higher curriculum, CEFR A1/A2/B1/B2,
and essential academic/school vocabulary.
"""

import json
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_OUT = os.path.join(BASE_DIR, 'data', 'full_dictionary.json')
JS_LOOKUP = os.path.join(BASE_DIR, 'js', 'word_lookup.js')

# Core dictionary dictionary
dictionary = {}

def add_word(en, tr, pos="Kelime", icon="📖"):
    if not en or not tr:
        return
    en_clean = en.strip().lower()
    if en_clean not in dictionary:
        dictionary[en_clean] = {
            "tr": tr.strip(),
            "type": pos.lower(),
            "type_label": pos,
            "icon": icon,
            "wordEn": en_clean
        }

# 1. Import from data_definitions & generate_full_curriculum if available
try:
    sys.path.append(os.path.join(BASE_DIR, 'scripts'))
    from generate_full_curriculum import A2_VERBS_RAW, B1_VERBS_RAW
    from data_definitions import (
        NOUNS_DATA, ADJECTIVES_DATA, ADVERBS_DATA,
        PREPOSITIONS_DATA, PHRASAL_VERBS_DATA, IDIOMS_DATA, CONJUNCTIONS_DATA
    )

    for item in A2_VERBS_RAW + B1_VERBS_RAW:
        # (en, tr, v2, v3, ing, s_form, ...)
        en, tr, v2, v3, ing, s_form = item[0], item[1], item[2], item[3], item[4], item[5]
        add_word(en, tr, "Fiil (Verb)", "🔵")
        add_word(v2, f"{tr} (Geçmiş Zaman / V2)", "Geçmiş Zaman Fiil (V2)", "🔵")
        add_word(v3, f"{tr} (3. Hali / V3)", "Past Participle (V3)", "🔵")
        add_word(ing, f"{tr} (Şimdiki Zaman / -ing)", "Şimdiki Zaman Fiil (V-ing)", "🔵")
        add_word(s_form, f"{tr} (Geniş Zaman / 3. Tekil)", "Geniş Zaman Fiil (3. Tekil)", "🔵")

    for item in NOUNS_DATA:
        add_word(item[0], item[1], item[2] if len(item)>2 else "İsim (Noun)", "🔴")
    for item in ADJECTIVES_DATA:
        add_word(item[0], item[1], item[2] if len(item)>2 else "Sıfat (Adjective)", "🟩")
    for item in ADVERBS_DATA:
        add_word(item[0], item[1], item[2] if len(item)>2 else "Zarf (Adverb)", "🟣")
    for item in PREPOSITIONS_DATA:
        add_word(item[0], item[1], item[2] if len(item)>2 else "Edat (Preposition)", "🟡")
    for item in PHRASAL_VERBS_DATA:
        add_word(item[0], item[1], "Deyimsel Fiil (Phrasal Verb)", "⚡")
    for item in IDIOMS_DATA:
        add_word(item[0], item[1], "Deyim / Kalıp (Idiom)", "💡")
    for item in CONJUNCTIONS_DATA:
        add_word(item[0], item[1], item[2] if len(item)>2 else "Bağlaç (Conjunction)", "🔗")
except Exception as e:
    print("Notice importing modules:", e)

# 2. Import all words from school_fly_higher.json
try:
    school_json = os.path.join(BASE_DIR, 'data', 'school_fly_higher.json')
    if os.path.exists(school_json):
        with open(school_json, 'r', encoding='utf-8') as f:
            s_data = json.load(f)
        for u in s_data.get('units', []):
            for w in u.get('words', []):
                add_word(w.get('en'), w.get('tr'), w.get('pos', '9. Sınıf Kelime'), "🏫")
except Exception as e:
    print("Notice loading school_fly_higher.json:", e)

# 3. Essential 9th Grade, Grammar, Book & Academic Vocabulary
EXTENDED_VOCABULARY = [
    # Pronouns & Determiners & Quantifiers
    ("more", "daha fazla, daha çok", "Miktar Belirteci / Zarf", "📊"),
    ("most", "en çok, en fazla, çoğu", "Belirteç / Sıfat", "📊"),
    ("less", "daha az", "Belirteç / Zarf", "📊"),
    ("least", "en az", "Belirteç / Sıfat", "📊"),
    ("also", "ayrıca, de / da, aynı zamanda", "Zarf (Adverb)", "🟣"),
    ("too", "aşırı, fazla / -de, -da", "Zarf (Degree / Addition)", "🟣"),
    ("enough", "yeterli, yeterince", "Belirteç / Zarf", "⚖️"),
    ("very", "çok, pek", "Derece Zarfı", "🟣"),
    ("many", "birçok, çok sayıda (sayılabilen)", "Belirteç (Quantifier)", "🔢"),
    ("much", "çok, fazla (sayılamayan)", "Belirteç (Quantifier)", "🔢"),
    ("some", "biraz, bazı, birkaç", "Belirteç (Quantifier)", "🔢"),
    ("any", "hiç, herhangi bir", "Belirteç (Quantifier)", "🔢"),
    ("each", "her bir, her", "Belirteç", "🔢"),
    ("every", "her, bütün", "Belirteç", "🔢"),
    ("all", "bütün, tüm, hepsi", "Belirteç", "🔢"),
    ("both", "her ikisi, her iki", "Belirteç", "🔢"),
    ("either", "ya ... ya da / ikisinden biri", "Bağlaç / Belirteç", "🔗"),
    ("neither", "ne ... ne de / hiçbirisi", "Bağlaç / Belirteç", "🔗"),
    ("none", "hiçbiri, hiç kimse", "Zamir", "🔢"),
    ("few", "az, birkaç (sayılabilen)", "Belirteç", "🔢"),
    ("little", "az (sayılamayan) / küçük", "Belirteç / Sıfat", "🔢"),
    ("several", "birkaç, birtakım", "Belirteç", "🔢"),
    ("other", "diğer, başka", "Sıfat / Zamir", "🟩"),
    ("another", "başka bir, diğer bir", "Belirteç / Zamir", "🟩"),
    ("such", "böyle, bu gibi, öylesine", "Belirteç", "🟩"),

    # Grammar & Linguistics Terms
    ("present", "şimdiki / mevcut / sunmak / hediye", "Sıfat / Fiil / İsim", "🎁"),
    ("simple", "basit, sade, yalın", "Sıfat (Adjective)", "🟩"),
    ("continuous", "sürekli, devam eden, şimdiki", "Sıfat (Adjective)", "🟩"),
    ("progressive", "ilerleyen, süregelen", "Sıfat (Adjective)", "🟩"),
    ("perfect", "kusursuz, mükemmel / tamamlanmış zaman", "Sıfat (Adjective)", "⭐"),
    ("past", "geçmiş, geçen / geçmiş zaman", "İsim / Sıfat", "⏳"),
    ("future", "gelecek, istikbal / gelecek zaman", "İsim / Sıfat", "🚀"),
    ("passive", "edilgen, pasif", "Sıfat (Grammar)", "📐"),
    ("active", "etken, aktif, faal", "Sıfat (Adjective)", "⚡"),
    ("conditional", "şartlı, koşullu (If Clause)", "Sıfat / İsim", "📐"),
    ("relative", "bağıl, göreli / akraba / sıfat cümleciği", "Sıfat / İsim", "🔗"),
    ("modal", "yardımcı kip (can, must, should)", "İsim (Grammar)", "📐"),
    ("verb", "fiil, eylem", "İsim (Grammar)", "🔵"),
    ("noun", "isim, ad", "İsim (Grammar)", "🔴"),
    ("adjective", "sıfat, önad", "İsim (Grammar)", "🟩"),
    ("adverb", "zarf, belirteç", "İsim (Grammar)", "🟣"),
    ("pronoun", "zamir, adıl", "İsim (Grammar)", "👤"),
    ("preposition", "edat, ilgeç (in, on, at, with)", "İsim (Grammar)", "🟡"),
    ("conjunction", "bağlaç (because, although, if)", "İsim (Grammar)", "🔗"),
    ("clause", "cümlecik, yan cümle", "İsim (Grammar)", "📝"),
    ("sentence", "cümle, tümce", "İsim (Grammar)", "💬"),
    ("structure", "yapı, bünye / yapılandırmak", "İsim / Fiil", "🏗️"),
    ("grammar", "dilbilgisi, gramer", "İsim (Education)", "📚"),
    ("vocabulary", "kelime hazinesi, sözcük dağarcığı", "İsim (Education)", "🔤"),
    ("tense", "zaman (dilbilgisinde)", "İsim (Grammar)", "⏳"),
    ("subject", "özne / ders, konu", "İsim (Grammar/School)", "👤"),
    ("object", "nesne, tümleç / itiraz etmek", "İsim / Fiil", "📦"),
    ("singular", "tekil", "Sıfat (Grammar)", "1️⃣"),
    ("plural", "çoğul", "Sıfat (Grammar)", "🔢"),
    ("affirmative", "olumlu (cümle)", "Sıfat (Grammar)", "✅"),
    ("negative", "olumsuz (cümle)", "Sıfat (Grammar)", "❌"),
    ("interrogative", "soru (cümlesi)", "Sıfat (Grammar)", "❓"),
    ("regular", "düzenli", "Sıfat (Adjective)", "🟩"),
    ("irregular", "düzensiz (fiil)", "Sıfat (Adjective)", "⚡"),
    ("infinitive", "mastar (to + V1)", "İsim (Grammar)", "📐"),
    ("gerund", "fiilimsi (-ing hali)", "İsim (Grammar)", "📐"),
    ("participle", "ortaç (V3 / -ing)", "İsim (Grammar)", "📐"),
    ("idiom", "deyim, tabir", "İsim (Language)", "💡"),
    ("expression", "ifade, anlatım, deyim", "İsim (Language)", "💬"),
    ("meaning", "anlam, mana", "İsim (Language)", "📖"),
    ("definition", "tanım, açıklama", "İsim (Language)", "📝"),
    ("pronunciation", "telaffuz, söyleniş", "İsim (Language)", "🔊"),
    ("translation", "çeviri, tercüme", "İsim (Language)", "🌐"),

    # Academic & School Vocabulary (Fly Higher 2.0 Themes)
    ("express", "ifade etmek, belirtmek / hızlı", "Fiil / Sıfat", "💬"),
    ("effectively", "etkili bir şekilde, başarıyla", "Durum Zarfı", "🟣"),
    ("effective", "etkili, tesirli", "Sıfat (Adjective)", "🟩"),
    ("form", "oluşturmak, biçimlendirmek / form, şekil", "Fiil / İsim", "📐"),
    ("forms", "biçimler, şekiller / oluşturur", "Çoğul İsim / Fiil", "📐"),
    ("bridge", "köprü kurmak / köprü", "Fiil / İsim", "🌉"),
    ("bridges", "köprüler / köprü kurar", "Çoğul İsim / Fiil", "🌉"),
    ("beginner", "başlangıç seviyesi, acemi", "İsim (Level)", "🌱"),
    ("basics", "temel bilgiler, esaslar", "Çoğul İsim", "📐"),
    ("basic", "temel, basit, esas", "Sıfat (Adjective)", "🟩"),
    ("complex", "karmaşık, girift / tesis", "Sıfat / İsim", "🧩"),
    ("complexity", "karmaşıklık", "İsim (Noun)", "🧩"),
    ("describe", "tanımlamak, betimlemek, tarif etmek", "Fiil (Verb)", "🔵"),
    ("description", "tanım, betimleme, açıklama", "İsim (Noun)", "📝"),
    ("descriptive", "betimleyici, tanımlayıcı", "Sıfat (Adjective)", "🟩"),
    ("habit", "alışkanlık, huy", "İsim (Noun)", "🔄"),
    ("habits", "alışkanlıklar", "Çoğul İsim", "🔄"),
    ("ability", "yetenek, kabiliyet, beceri", "İsim (Noun)", "⚡"),
    ("abilities", "yetenekler, beceriler", "Çoğul İsim", "⚡"),
    ("obligation", "zorunluluk, yükümlülük", "İsim (Noun)", "⚖️"),
    ("obligations", "zorunluluklar, yükümlülükler", "Çoğul İsim", "⚖️"),
    ("prohibition", "yasaklama, yasak", "İsim (Noun)", "🚫"),
    ("advice", "tavsiye, öğüt, nasihat", "İsim (Noun)", "💡"),
    ("advise", "tavsiye etmek, öğüt vermek", "Fiil (Verb)", "🔵"),
    ("rule", "kural, kaide / yönetmek", "İsim / Fiil", "📏"),
    ("rules", "kurallar", "Çoğul İsim", "📏"),
    ("exercise", "alıştırma, egzersiz / egzersiz yapmak", "İsim / Fiil", "🏋️"),
    ("exercises", "alıştırmalar, egzersizler", "Çoğul İsim", "🏋️"),
    ("practice", "pratik yapmak, alıştırma / uygulama", "Fiil / İsim", "🎯"),
    ("practicing", "pratik yaparak, çalışan", "Fiil (V-ing)", "🎯"),
    ("sustainable", "sürdürülebilir, devam ettirilebilir", "Sıfat (Environment)", "🌱"),
    ("sustainability", "sürdürülebilirlik", "İsim (Noun)", "🌱"),
    ("environment", "çevre, ortam", "İsim (Environment)", "🌍"),
    ("environmental", "çevresel", "Sıfat (Environment)", "🌍"),
    ("renewable", "yenilenebilir (enerji)", "Sıfat (Energy)", "♻️"),
    ("energy", "enerji, güç", "İsim (Science)", "⚡"),
    ("solar", "güneş, güneş enerjili", "Sıfat (Energy)", "☀️"),
    ("wind", "rüzgar / sarmak, kurmak", "İsim / Fiil", "💨"),
    ("power", "güç, enerji, iktidar / güç vermek", "İsim / Fiil", "⚡"),
    ("affordable", "uygun fiyatlı, bütçeye uygun", "Sıfat (Economy)", "💰"),
    ("afford", "parası yetmek, gücü yetmek", "Fiil (Verb)", "💰"),
    ("reduce", "azaltmak, eksiltmek, kısmak", "Fiil (Verb)", "📉"),
    ("reduction", "azalma, indirim", "İsim (Noun)", "📉"),
    ("carbon", "karbon", "İsim (Science)", "🧪"),
    ("footprint", "ayak izi", "İsim (Environment)", "👣"),
    ("recycle", "geri dönüştürmek", "Fiil (Environment)", "♻️"),
    ("recycling", "geri dönüşüm", "İsim / Fiil (V-ing)", "♻️"),
    ("avoid", "kaçınmak, sakınmak, önlemek", "Fiil (Verb)", "🛡️"),
    ("avoiding", "kaçınarak, sakınma", "Fiil (V-ing)", "🛡️"),
    ("plastic", "plastik / esnek", "İsim / Sıfat", "🛍️"),
    ("plastics", "plastikler", "Çoğul İsim", "🛍️"),
    ("immediate", "acil, derhal, dolaysız", "Sıfat (Time)", "⚡"),
    ("action", "eylem, hareket, aksiyon", "İsim (Noun)", "🎬"),
    ("generation", "nesil, kuşak / üretim", "İsim (Society)", "👥"),
    ("generations", "nesiller, kuşaklar", "Çoğul İsim", "👥"),
    ("greener", "daha yeşil, daha çevreci", "Karşılaştırma Sıfatı", "🌿"),
    ("green", "yeşil / çevreci", "Sıfat (Color/Eco)", "🌿"),
    ("planet", "gezegen, dünya", "İsim (Astronomy)", "🪐"),
    ("teenager", "genç, ergen (13-19 yaş)", "İsim (People)", "🧑"),
    ("teenagers", "gençler, ergenler", "Çoğul İsim", "🧑"),
    ("develop", "geliştirmek, geliştirmek, oluşmak", "Fiil (Verb)", "📈"),
    ("developing", "gelişen, geliştirmekte olan", "Fiil (V-ing)", "📈"),
    ("development", "gelişim, kalkınma", "İsim (Noun)", "📈"),
    ("protect", "korumak, muhafaza etmek", "Fiil (Verb)", "🛡️"),
    ("protection", "koruma, himaye", "İsim (Noun)", "🛡️"),
    ("solution", "çözüm, çare / çözelti", "İsim (Noun)", "💡"),
    ("solutions", "çözümler", "Çoğul İsim", "💡"),
    ("enjoy", "zevk almak, tadını çıkarmak, hoşlanmak", "Fiil (Verb)", "🎉"),
    ("enjoyable", "keyifli, eğlenceli", "Sıfat (Adjective)", "🎉"),
    ("method", "yöntem, metot, usul", "İsim (Noun)", "📐"),
    ("methods", "yöntemler", "Çoğul İsim", "📐"),
    ("algorithm", "algoritma", "İsim (Technology)", "💻"),
    ("algorithms", "algoritmalar", "Çoğul İsim", "💻"),
    ("performance", "performans, başarım, temsil", "İsim (Noun)", "🏆"),
    ("provide", "sağlamak, temin etmek, sunmak", "Fiil (Verb)", "🤝"),
    ("provides", "sağlar, sunar", "Geniş Zaman Fiil", "🤝"),
    ("feedback", "geri bildirim, dönüt", "İsim (Education)", "💬"),
    ("cybersecurity", "siber güvenlik", "İsim (Tech)", "🔒"),
    ("privacy", "gizlilik, mahremiyet", "İsim (Tech)", "🛡️"),
    ("concern", "endişe, kaygı / ilgilendirmek", "İsim / Fiil", "😟"),
    ("concerns", "endişeler, kaygılar", "Çoğul İsim", "😟"),
    ("dilemma", "ikilem, çıkmaz, tereddüt", "İsim (Noun)", "🤔"),
    ("dilemmas", "ikilemler", "Çoğul İsim", "🤔"),
    ("society", "toplum, cemiyet", "İsim (Society)", "🏛️"),
    ("acquire", "edinmek, kazanmak, elde etmek", "Fiil (Verb)", "🎓"),
    ("essential", "temel, zorunlu, hayati", "Sıfat (Adjective)", "⭐"),
    ("skill", "beceri, yetenek, ustalık", "İsim (Noun)", "🎯"),
    ("skills", "beceriler, yetenekler", "Çoğul İsim", "🎯"),
    ("critical", "eleştirel, kritik, çok önemli", "Sıfat (Adjective)", "🧠"),
    ("thinking", "düşünme, düşünce", "İsim / Fiil (V-ing)", "🧠"),
    ("admire", "hayran olmak, takdir etmek", "Fiil (Verb)", "👏"),
    ("admires", "hayran olur, takdir eder", "Geniş Zaman Fiil", "👏"),
    ("innovator", "yenilikçi, mucit", "İsim (People)", "💡"),
    ("innovators", "yenilikçiler, mucitler", "Çoğul İsim", "💡"),
    ("accomplish", "başarmak, tamamlamak, üstesinden gelmek", "Fiil (Verb)", "🏆"),
    ("remarkable", "olağanüstü, dikkate değer, harika", "Sıfat (Adjective)", "✨"),
    ("perseverance", "azim, sebat, kararlılık", "İsim (Character)", "💪"),
    ("cheerful", "neşeli, şen, güler yüzlü", "Sıfat (Character)", "😊"),
    ("confident", "özgüvenli, kendinden emin", "Sıfat (Character)", "🦁"),
    ("inspiration", "ilham kaynağı, esin", "İsim (Noun)", "✨"),
    ("famous", "ünlü, meşhur, tanınmış", "Sıfat (Adjective)", "🌟"),
    ("painting", "tablo, resim / boyama", "İsim (Art)", "🎨"),
    ("stolen", "çalınmış (steal fiilinin V3 hali)", "Past Participle (V3)", "🕵️"),
    ("steal", "çalmak, hırsızlık yapmak", "Fiil (Verb)", "🕵️"),
    ("stole", "çaldı (geçmiş zaman / V2)", "Geçmiş Zaman Fiil (V2)", "🕵️"),
    ("experiment", "deney / deney yapmak", "İsim / Fiil", "🔬"),
    ("science", "bilim, fen", "İsim (Education)", "🔬"),
    ("scientific", "bilimsel", "Sıfat (Science)", "🔬"),
    ("ocean", "okyanus", "İsim (Geography)", "🌊"),
    ("oceans", "okyanuslar", "Çoğul İsim", "🌊"),
    ("tree", "ağaç", "İsim (Nature)", "🌳"),
    ("trees", "ağaçlar", "Çoğul İsim", "🌳"),
    ("warming", "ısınma, küresel ısınma", "İsim / Fiil (V-ing)", "🌡️"),
    ("decrease", "azalmak, düşmek / düşüş", "Fiil / İsim", "📉"),
    ("increase", "artmak, çoğalmak / artış", "Fiil / İsim", "📈"),
    ("library", "kütüphane", "İsim (Place)", "📚"),
    ("quiet", "sessiz, sakin", "Sıfat (Adjective)", "🤫"),
    ("peer", "akran, yaşıt / dikkatle bakmak", "İsim / Fiil", "👥"),
    ("peers", "akranlar, yaşıtlar", "Çoğul İsim", "👥"),
    ("curiosity", "merak, ilgi", "İsim (Noun)", "🔍"),
    ("curious", "meraklı, ilgi duyan", "Sıfat (Adjective)", "🔍"),
    ("innovative", "yenilikçi, inovatif", "Sıfat (Adjective)", "💡"),
    ("gadget", "teknolojik alet, cihaz", "İsim (Tech)", "📱"),
    ("gadgets", "teknolojik aletler", "Çoğul İsim", "📱"),
    ("dream", "rüya, hayal / hayal kurmak", "İsim / Fiil", "💭"),
    ("dreams", "hayaller, rüyalar", "Çoğul İsim", "💭"),
    ("schedule", "ders programı, takvim / planlamak", "İsim / Fiil", "📅"),
    ("schedules", "programlar, takvimler", "Çoğul İsim", "📅"),
    ("leisure", "boş vakit, serbest zaman", "İsim (Noun)", "☕"),
    ("connect", "bağlanmak, bağlamak, ilişki kurmak", "Fiil (Verb)", "🔗"),
    ("connecting", "bağlanarak, bağlantı", "Fiil (V-ing)", "🔗"),
    ("connection", "bağlantı, ilişki", "İsim (Noun)", "🔗"),
    ("connections", "bağlantılar, ilişkiler", "Çoğul İsim", "🔗"),
    ("interaction", "etkileşim, iletişim", "İsim (Noun)", "💬"),
    ("interactions", "etkileşimler", "Çoğul İsim", "💬"),
    ("belong", "ait olmak, dahil olmak", "Durum Fiili (State Verb)", "🏷️"),
    ("belongs", "ait olur (3. tekil)", "Geniş Zaman Fiil", "🏷️"),
    ("keen", "meraklı, hevesli, keskin", "Sıfat (Adjective)", "🎯"),
    ("prefer", "tercih etmek, yeğlemek", "Durum Fiili (State Verb)", "⭐"),
    ("prefers", "tercih eder (3. tekil)", "Geniş Zaman Fiil", "⭐"),
    ("preference", "tercih, öncelik", "İsim (Noun)", "⭐"),
    ("enthusiastic", "hevesli, coşkulu, istekli", "Sıfat (Character)", "🔥"),
    ("enthusiasm", "heves, coşku, şevk", "İsim (Noun)", "🔥"),
    ("routine", "günlük rutin, alışkanlık / sıradan", "İsim / Sıfat", "🔄"),
    ("routines", "rutinler, alışkanlıklar", "Çoğul İsim", "🔄"),
    ("opportunity", "fırsat, olanak, imkan", "İsim (Noun)", "🚪"),
    ("opportunities", "fırsatlar, olanaklar", "Çoğul İsim", "🚪"),
    ("balance", "denge / dengelemek", "İsim / Fiil", "⚖️"),
    ("secret", "sır, gizem / gizli", "İsim / Sıfat", "🔑"),
    ("success", "başarı, muvaffakiyet", "İsim (Noun)", "🏆"),
    ("successful", "başarılı", "Sıfat (Adjective)", "🏆"),
    ("competitive", "rekabetçi, hırslı", "Sıfat (Adjective)", "⚔️"),
    ("competition", "yarışma, rekabet, müsabaka", "İsim (Noun)", "🏆"),
    ("creative", "yaratıcı, üretken", "Sıfat (Adjective)", "🎨"),
    ("creativity", "yaratıcılık", "İsim (Noun)", "🎨"),
    ("create", "yaratmak, oluşturmak", "Fiil (Verb)", "🎨"),
    ("created", "oluşturdu / oluşturulmuş", "Geçmiş Zaman / V3", "🎨"),
    ("digital", "dijital, sayısal", "Sıfat (Tech)", "💻"),
    ("traditional", "geleneksel, ananevi", "Sıfat (Culture)", "📜"),
    ("transform", "dönüştürmek, değiştirmek", "Fiil (Verb)", "🔄"),
    ("transforming", "dönüştüren, dönüşüm", "Fiil (V-ing)", "🔄"),
    ("speed", "hız, sürat / hızlanmak", "İsim / Fiil", "⚡"),
    ("incredible", "inanılmaz, olağanüstü", "Sıfat (Adjective)", "😲"),
    ("analyze", "analiz etmek, incelemek, çözümlemek", "Fiil (Verb)", "🔍"),
    ("analyzing", "analiz ederek, inceleyen", "Fiil (V-ing)", "🔍"),
    ("analysis", "analiz, çözümleme, tahlil", "İsim (Noun)", "📊"),
    ("personalized", "kişiselleştirilmiş, özel", "Sıfat (Education)", "👤"),
    ("personal", "kişisel, şahsi", "Sıfat (Adjective)", "👤"),
    ("significant", "önemli, kayda değer, anlamlı", "Sıfat (Adjective)", "⭐"),
    ("sacrifice", "feda etmek, kurban etmek / fedakarlık", "Fiil / İsim", "🕊️"),
    ("sacrificing", "feda ederek", "Fiil (V-ing)", "🕊️"),
    ("investigate", "araştırmak, soruşturmak", "Fiil (Verb)", "🕵️"),
    ("investigation", "araştırma, soruşturma", "İsim (Noun)", "🕵️"),
    ("discover", "keşfetmek, bulmak", "Fiil (Verb)", "🧭"),
    ("discovered", "keşfetti / keşfedilmiş", "Geçmiş Zaman / V3", "🧭"),
    ("discovery", "keşif, buluş", "İsim (Noun)", "🧭"),
    ("invent", "icat etmek, bulmak", "Fiil (Verb)", "💡"),
    ("invented", "icat etti / icat edilmiş", "Geçmiş Zaman / V3", "💡"),
    ("invention", "icat, buluş", "İsim (Noun)", "💡"),
    ("produce", "üretmek, imal etmek", "Fiil (Verb)", "🏭"),
    ("produced", "üretti / üretilmiş", "Geçmiş Zaman / V3", "🏭"),
    ("product", "ürün, mahsul", "İsim (Noun)", "📦"),
    ("production", "üretim, yapım", "İsim (Noun)", "🏭"),
    ("athlete", "sporcu, atlet", "İsim (Sports)", "🏃"),
    ("athletes", "sporcular, atletler", "Çoğul İsim", "🏃"),
    ("coach", "antrenör, koç / eğitmek", "İsim / Fiil", "📋"),
    ("trainer", "eğitmen, antrenör", "İsim (People)", "📋"),
    ("student", "öğrenci", "İsim (School)", "🎒"),
    ("students", "öğrenciler", "Çoğul İsim", "🎒"),
    ("teacher", "öğretmen", "İsim (School)", "👩‍🏫"),
    ("teachers", "öğretmenler", "Çoğul İsim", "👩‍🏫"),
    ("class", "sınıf, ders", "İsim (School)", "🏫"),
    ("classes", "sınıflar, dersler", "Çoğul İsim", "🏫"),
    ("classroom", "derslik, sınıf", "İsim (School)", "🏫"),
    ("school", "okul / eğitmek", "İsim / Fiil", "🏫"),
    ("high school", "lise", "İsim (School)", "🏫"),
    ("university", "üniversite", "İsim (School)", "🎓"),
    ("college", "kolej, fakülte, yüksekokul", "İsim (School)", "🎓"),
    ("book", "kitap / rezervasyon yapmak", "İsim / Fiil", "📖"),
    ("books", "kitaplar", "Çoğul İsim", "📖"),
    ("workbook", "çalışma kitabı", "İsim (School)", "📒"),
    ("notebook", "defter, not defteri", "İsim (School)", "📓"),
    ("page", "sayfa / seslenmek", "İsim / Fiil", "📄"),
    ("pages", "sayfalar", "Çoğul İsim", "📄"),
    ("chapter", "bölüm, fasıl", "İsim (Book)", "📑"),
    ("story", "hikaye, öykü / kat", "İsim (Literature)", "📖"),
    ("stories", "hikayeler, öyküler", "Çoğul İsim", "📖"),
    ("passage", "metin parçası, pasaj / geçit", "İsim (Literature)", "📜"),
    ("word", "kelime, sözcük", "İsim (Language)", "🔤"),
    ("words", "kelimeler, sözcükler", "Çoğul İsim", "🔤"),
    ("read", "okumak", "Fiil (Verb)", "📖"),
    ("reading", "okuma / okuyarak", "İsim / Fiil (V-ing)", "📖"),
    ("write", "yazmak", "Fiil (Verb)", "✍️"),
    ("writing", "yazı / yazarak", "İsim / Fiil (V-ing)", "✍️"),
    ("written", "yazılmış (write fiilinin V3 hali)", "Past Participle (V3)", "✍️"),
    ("speak", "konuşmak", "Fiil (Verb)", "🗣️"),
    ("speaking", "konuşma / konuşarak", "İsim / Fiil (V-ing)", "🗣️"),
    ("spoken", "konuşulan / konuşulmuş", "Past Participle (V3)", "🗣️"),
    ("listen", "dinlemek, kulak vermek", "Fiil (Verb)", "👂"),
    ("listening", "dinleme / dinleyerek", "İsim / Fiil (V-ing)", "👂"),
    ("learn", "öğrenmek", "Fiil (Verb)", "🧠"),
    ("learning", "öğrenme / öğrenim", "İsim / Fiil (V-ing)", "🧠"),
    ("learned", "öğrendi / öğrenilmiş", "Geçmiş Zaman / V3", "🧠"),
    ("study", "ders çalışmak, incelemek / çalışma", "Fiil / İsim", "📚"),
    ("studying", "ders çalışarak, inceleyen", "Fiil (V-ing)", "📚"),
    ("studies", "ders çalışır / çalışmalar", "Fiil / Çoğul İsim", "📚"),
    ("test", "test, sınav / test etmek", "İsim / Fiil", "📝"),
    ("tests", "testler, sınavlar", "Çoğul İsim", "📝"),
    ("exam", "sınav, yazılı", "İsim (School)", "📝"),
    ("exams", "sınavlar", "Çoğul İsim", "📝"),
    ("quiz", "küçük sınav, bilgi yarışması", "İsim (School)", "❓"),
    ("question", "soru / sorgulamak", "İsim / Fiil", "❓"),
    ("questions", "sorular", "Çoğul İsim", "❓"),
    ("answer", "cevap, yanıt / cevaplamak", "İsim / Fiil", "💡"),
    ("answers", "cevaplar / cevaplar", "Çoğul İsim / Fiil", "💡"),
    ("score", "puan, skor / puan almak", "İsim / Fiil", "🎯"),
    ("result", "sonuç, netice / sonuçlanmak", "İsim / Fiil", "📊"),
    ("results", "sonuçlar", "Çoğul İsim", "📊"),
    ("grade", "not / sınıf derecesi / puanlamak", "İsim / Fiil", "🎒"),
    ("ninth", "dokuzuncu (9.)", "Sıra Sayısı", "9️⃣"),
    ("tenth", "onuncu (10.)", "Sıra Sayısı", "🔟"),
    ("first", "birinci, ilk / ilk olarak", "Sıra Sayısı / Zarf", "1️⃣"),
    ("second", "ikinci / saniye", "Sıra Sayısı / İsim", "2️⃣"),
    ("third", "üçüncü", "Sıra Sayısı", "3️⃣"),
    ("unit", "ünite, birim", "İsim (School)", "📦"),
    ("units", "üniteler", "Çoğul İsim", "📦"),
    ("lesson", "ders, ibret", "İsim (School)", "🎓"),
    ("lessons", "dersler", "Çoğul İsim", "🎓"),
    ("starter", "başlangıç, başlangıç ünitesi", "İsim (School)", "👋"),
    ("welcome", "hoş geldiniz / hoş karşılamak", "Ünlem / Fiil", "👋"),
    ("topic", "konu, başlık, mevzu", "İsim (Noun)", "📌"),
    ("topics", "konular, başlıklar", "Çoğul İsim", "📌"),
    ("theme", "tema, ana fikir", "İsim (Noun)", "🎨"),
    ("project", "proje / yansıtmak, planlamak", "İsim / Fiil", "📊"),
    ("projects", "projeler", "Çoğul İsim", "📊"),
    ("homework", "ev ödevi", "İsim (School)", "✏️"),
    ("assignment", "ödev, görev, atama", "İsim (School)", "📋"),
    ("task", "görev, iş", "İsim (Noun)", "✅"),
    ("tasks", "görevler, işler", "Çoğul İsim", "✅"),
    ("goal", "hedef, amaç / gol", "İsim (Noun)", "🎯"),
    ("goals", "hedefler, amaçlar", "Çoğul İsim", "🎯"),
    ("dream", "rüya, hayal / hayal kurmak", "İsim / Fiil", "💭"),
    ("career", "kariyer, meslek", "İsim (Work)", "💼"),
    ("careers", "kariyerler, meslekler", "Çoğul İsim", "💼"),
    ("job", "iş, meslek, görev", "İsim (Work)", "💼"),
    ("profession", "meslek, uzmanlık", "İsim (Work)", "💼"),
    ("entrepreneurship", "girişimcilik", "İsim (Business)", "🚀"),
    ("entrepreneur", "girişimci", "İsim (People)", "🚀"),
    ("opportunity", "fırsat, imkan", "İsim (Noun)", "🚪"),
    ("international", "uluslararası, beynelmilel", "Sıfat (Geography)", "🌐"),
    ("national", "ulusal, milli", "Sıfat (Geography)", "🇹🇷"),
    ("global", "küresel, dünya çapında", "Sıfat (Geography)", "🌍"),
    ("citizen", "vatandaş, yurttaş", "İsim (Society)", "👤"),
    ("citizens", "vatandaşlar, yurttaşlar", "Çoğul İsim", "👥"),
    ("citizenship", "vatandaşlık, yurttaşlık", "İsim (Society)", "🏛️"),
    ("culture", "kültür, ekin", "İsim (Society)", "🎭"),
    ("cultural", "kültürel", "Sıfat (Culture)", "🎭"),
    ("art", "sanat / hüner", "İsim (Art)", "🎨"),
    ("arts", "sanatlar", "Çoğul İsim", "🎨"),
    ("artist", "sanatçı, ressam", "İsim (People)", "🎨"),
    ("music", "müzik", "İsim (Art)", "🎵"),
    ("cinema", "sinema", "İsim (Media)", "🎬"),
    ("movie", "film, sinema filmi", "İsim (Media)", "🎬"),
    ("film", "film / film çekmek", "İsim / Fiil", "🎬"),
    ("media", "medya, basın-yayın", "İsim (Media)", "📺"),
    ("news", "haber, haberler", "İsim (Media)", "📰"),
    ("health", "sağlık, sıhhat", "İsim (Health)", "❤️"),
    ("healthy", "sağlıklı, sıhhatli", "Sıfat (Health)", "🥗"),
    ("nutrition", "beslenme, gıda", "İsim (Health)", "🍎"),
    ("harmony", "uyum, ahenk", "İsim (Noun)", "🕊️"),
    ("mind", "zihin, akıl / önemsemek, aldırmak", "İsim / Fiil", "🧠"),
    ("body", "beden, vücut, gövde", "İsim (Biology)", "🧍"),
    ("nature", "doğa, tabiat / mizaç", "İsim (Nature)", "🌲"),
    ("natural", "doğal, tabii", "Sıfat (Nature)", "🌲"),
    ("wildlife", "yaban hayatı", "İsim (Nature)", "🦁"),
    ("climate", "iklim", "İsim (Geography)", "🌦️"),
    ("action", "eylem, hareket", "İsim (Noun)", "🎬"),
    ("climate action", "iklim eylemi / mücadelesi", "İsim (Environment)", "🌍"),
    ("warrior", "savaşçı, cengaver", "İsim (People)", "⚔️"),
    ("eco-warrior", "çevre savaşçısı", "İsim (People)", "🌱"),
    ("adventure", "macera, serüven", "İsim (Noun)", "🧭"),
    ("adventures", "maceralar", "Çoğul İsim", "🧭"),
    ("wonder", "harika, mucize / merak etmek", "İsim / Fiil", "✨"),
    ("wonders", "harikalar", "Çoğul İsim", "✨"),
    ("identity", "kimlik, kişilik", "İsim (Society)", "🆔"),
    ("passion", "tutku, coşku, heves", "İsim (Emotion)", "🔥"),
    ("passions", "tutkular", "Çoğul İsim", "🔥"),
    ("lifestyle", "yaşam tarzı, hayat biçimi", "İsim (Society)", "🛋️"),
    ("lifestyles", "yaşam tarzları", "Çoğul İsim", "🛋️"),
    ("memory", "hafıza, anı, bellek", "İsim (Mind)", "🧠"),
    ("memories", "anılar, hatıralar", "Çoğul İsim", "📸"),
    ("milestone", "dönüm noktası, kilometre taşı", "İsim (Noun)", "🚩"),
    ("milestones", "dönüm noktaları", "Çoğul İsim", "🚩"),
    ("experience", "deneyim, tecrübe / deneyimlemek", "İsim / Fiil", "⭐"),
    ("experiences", "deneyimler, tecrübeler", "Çoğul İsim", "⭐"),
    ("achievement", "başarı, kazanım", "İsim (Noun)", "🏆"),
    ("achievements", "başarılar", "Çoğul İsim", "🏆"),
    ("horizon", "ufuk", "İsim (Geography)", "🌅"),
    ("horizons", "ufuklar", "Çoğul İsim", "🌅"),
    ("innovation", "yenilik, inovasyon", "İsim (Tech)", "💡"),
    ("innovations", "yenilikler, buluşlar", "Çoğul İsim", "💡"),
    ("dilemma", "ikilem, çıkmaz", "İsim (Noun)", "🤔"),
    ("dilemmas", "ikilemler", "Çoğul İsim", "🤔"),
    ("choice", "seçim, tercih", "İsim (Noun)", "👉"),
    ("choices", "seçimler, tercihler", "Çoğul İsim", "👉"),
    ("right", "doğru, hak / sağ taraf", "İsim / Sıfat", "⚖️"),
    ("rights", "haklar", "Çoğul İsim", "⚖️")
]

for item in EXTENDED_VOCABULARY:
    add_word(item[0], item[1], item[2], item[3] if len(item)>3 else "📖")

# 4. Write data/full_dictionary.json
with open(JSON_OUT, 'w', encoding='utf-8') as f:
    json.dump(dictionary, f, ensure_ascii=False, indent=2)

print(f"Generated full_dictionary.json with {len(dictionary)} words!")
